version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-app
    ports:
      - "3000:3000"
    env_file:
      - .env.production.local
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - app-network
    # Using PM2 to run the application from the compose file
    command: pm2-runtime app.js --name "nodejs-app"

  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - app-network
    command: mongod --replSet replicaSet01 --bind_ip_all

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: